name: Continuous Integration pipeline

on:
  push:

jobs:
  install:
    uses: ./.github/workflows/install.yml

  lint:
    needs: install
    uses: ./.github/workflows/lint.yml

  unit_test:
    needs: lint
    uses: ./.github/workflows/unit-test.yml
