name: Install Project Dependencies Action

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install packages
        run: npm install
