name: "Production: Deliver to S3 and Deploy to CloudFront"
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_PROD_API_URL }}
      VITE_API_VERSION: ${{ secrets.VITE_PROD_API_VERSION }}
      VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build Vite
        run: npm run build

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_PRODUCTION_BUCKET }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PRODUCTION_DISTRIBUTION }} --paths "/index.html" "/"
